/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        paper: '#fdfbf7',
        pencil: '#2d2d2d',
        muted: '#e5e0d8',
        marker: '#ff4d4d',
        pen: '#2d5da1',
        postit: '#fff9c4',
        leaf: '#2f8f4e',
      },
      fontFamily: {
        heading: ['Kalam', 'cursive'],
        body: ['"Patrick Hand"', 'cursive'],
      },
      borderRadius: {
        wobbly: '255px 15px 225px 15px / 15px 225px 15px 255px',
        wobblyMd: '15px 225px 15px 255px / 255px 15px 225px 15px',
        wobblySm: '12px 30px 14px 28px / 28px 14px 30px 12px',
        blob: '60% 40% 55% 45% / 45% 55% 40% 60%',
      },
      boxShadow: {
        hard: '4px 4px 0px 0px #2d2d2d',
        hardSm: '2px 2px 0px 0px #2d2d2d',
        hardLg: '8px 8px 0px 0px #2d2d2d',
        soft: '3px 3px 0px 0px rgba(45,45,45,0.1)',
      },
      keyframes: {
        bob: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
        pop: { '0%': { transform: 'scale(.9) rotate(-2deg)', opacity: 0 }, '100%': { transform: 'scale(1) rotate(0)', opacity: 1 } },
        stamp: { '0%': { transform: 'scale(2.2) rotate(-18deg)', opacity: 0 }, '100%': { transform: 'scale(1) rotate(-12deg)', opacity: 1 } },
        pulseRing: { '0%': { boxShadow: '0 0 0 0 rgba(255,77,77,.5)' }, '100%': { boxShadow: '0 0 0 18px rgba(255,77,77,0)' } },
        rise: { '0%': { transform: 'translateY(14px) rotate(-1deg)', opacity: 0 }, '100%': { transform: 'none', opacity: 1 } },
        pageIn: { '0%': { transform: 'translateY(10px) scale(.985)', opacity: 0 }, '100%': { transform: 'none', opacity: 1 } },
        inLeft: { '0%': { transform: 'translateX(-28px) rotate(-5deg) scale(.9)', opacity: 0 }, '60%': { transform: 'translateX(3px) rotate(-.5deg) scale(1.02)', opacity: 1 }, '100%': { transform: 'none', opacity: 1 } },
        inRight: { '0%': { transform: 'translateX(28px) rotate(5deg) scale(.9)', opacity: 0 }, '60%': { transform: 'translateX(-3px) rotate(.5deg) scale(1.02)', opacity: 1 }, '100%': { transform: 'none', opacity: 1 } },
        flipIn: { '0%': { transform: 'perspective(900px) rotateX(-70deg) translateY(-10px)', opacity: 0 }, '70%': { transform: 'perspective(900px) rotateX(8deg)', opacity: 1 }, '100%': { transform: 'perspective(900px) rotateX(0)', opacity: 1 } },
        wiggle: { '0%,100%': { transform: 'rotate(0)' }, '20%': { transform: 'rotate(-12deg)' }, '40%': { transform: 'rotate(10deg)' }, '60%': { transform: 'rotate(-6deg)' }, '80%': { transform: 'rotate(3deg)' } },
        dot: { '0%,60%,100%': { transform: 'translateY(0)', opacity: '.35' }, '30%': { transform: 'translateY(-7px)', opacity: '1' } },
        word: { '0%': { opacity: 0, transform: 'translateY(6px)', filter: 'blur(2px)' }, '100%': { opacity: 1, transform: 'none', filter: 'none' } },
        draw: { '0%': { strokeDashoffset: 'var(--len, 1000)' }, '100%': { strokeDashoffset: '0' } },
        marquee: { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        float: { '0%,100%': { transform: 'translateY(0) rotate(var(--r, 0deg))' }, '50%': { transform: 'translateY(-12px) rotate(calc(var(--r, 0deg) + 3deg))' } },
        toastIn: { '0%': { transform: 'translateY(-120%) rotate(-8deg)', opacity: 0 }, '55%': { transform: 'translateY(8px) rotate(3deg)', opacity: 1 }, '75%': { transform: 'translateY(-3px) rotate(0deg)' }, '100%': { transform: 'rotate(0deg)' } },
        blink: { '0%,92%,100%': { transform: 'scaleY(1)' }, '96%': { transform: 'scaleY(.1)' } },
        grow: { '0%': { transform: 'scaleY(0)' }, '100%': { transform: 'scaleY(1)' } },
        phoneIn: {
          '0%': { transform: 'translateY(160px) rotateX(55deg) rotateY(-35deg) rotateZ(8deg) scale(.7)', opacity: 0 },
          '60%': { opacity: 1 },
          '100%': { transform: 'none', opacity: 1 },
        },
        popIn: { '0%': { transform: 'scale(.4) translateY(12px)', opacity: 0 }, '70%': { transform: 'scale(1.06)', opacity: 1 }, '100%': { transform: 'none', opacity: 1 } },
        highlight: { '0%': { transform: 'scaleX(0) rotate(-1.5deg)' }, '100%': { transform: 'scaleX(1) rotate(-1.5deg)' } },
        token: { '0%': { opacity: 0, filter: 'blur(4px)' }, '100%': { opacity: 1, filter: 'none' } },
        twinkle: { '0%,100%': { transform: 'scale(1) rotate(0)', opacity: 1 }, '50%': { transform: 'scale(.6) rotate(45deg)', opacity: '.5' } },
      },
      animation: {
        bob: 'bob 3s ease-in-out infinite',
        pop: 'pop .18s ease-out',
        stamp: 'stamp .35s cubic-bezier(.2,1.6,.4,1) forwards',
        pulseRing: 'pulseRing 1.1s ease-out infinite',
        rise: 'rise .45s cubic-bezier(.2,.9,.3,1.2) backwards',
        pageIn: 'pageIn .32s cubic-bezier(.2,.9,.3,1) backwards',
        inLeft: 'inLeft .42s cubic-bezier(.2,.9,.3,1) backwards',
        inRight: 'inRight .42s cubic-bezier(.2,.9,.3,1) backwards',
        flipIn: 'flipIn .6s cubic-bezier(.2,.9,.3,1) backwards',
        wiggle: 'wiggle .5s ease-in-out',
        dot: 'dot 1.1s ease-in-out infinite',
        word: 'word .35s ease-out backwards',
        draw: 'draw 1.4s ease-out backwards',
        marquee: 'marquee 28s linear infinite',
        float: 'float 5s ease-in-out infinite',
        toastIn: 'toastIn .6s cubic-bezier(.2,.9,.3,1) backwards',
        blink: 'blink 4s ease-in-out infinite',
        grow: 'grow .6s cubic-bezier(.2,.9,.3,1.2) backwards',
        phoneIn: 'phoneIn 1.4s cubic-bezier(.16,1,.3,1) backwards',
        popIn: 'popIn .45s cubic-bezier(.2,.9,.3,1.3) backwards',
        twinkle: 'twinkle 2.2s ease-in-out infinite',
        token: 'token .5s ease-out backwards',
        highlight: 'highlight .7s cubic-bezier(.6,0,.2,1) .45s backwards',
      },
    },
  },
  plugins: [],
}
